config/routes.rb
Rails.application.routes.draw do

  resources :favorites
  get 'recipes/search'

  get 'recipes/show'

  get 'recipes/browse'

  get 'sessions/new'

  get 'users/new'

  get 'pages/login'

  get 'sessions/profile'

  get 'pages/home'

  get 'add' => 'favorites#new'

  get 'favorites/success'

	get 'login' => 'sessions#new'
	get 'profile' => 'sessions#profile'
	resources :sessions
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'

	get 'register' => 'users#new'

	get 'home' => 'pages#home'
	
	get 'contact'=>'pages#contact'
	get 'browse'=>'recipes#browse'

	get '/' => 'pages#home'

	resources :users
	
	get '/pages/search_results' => 'pages#search_results'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/recipe.rb
require 'httparty'

class Recipe
    include HTTParty

    #define API base URL and key for project
    ENV['FOOD2FORK_API_KEY'] = 'cd9872776e3e9b099a47c6ca92ea738c'
    base_uri 'http://food2fork.com/api'
    default_params key: ENV['FOOD2FORK_API_KEY']
    format :json

    #search method
    def self.for term        
        get('/search', query: { q: term }) ["recipes"]
    end

    #show method
    def self.find term
    	get('/get', query: { rId: term }) ["recipe"]
	end
	
	def self.browse term
		get('/browse', query: { q: term }) ["recipes"]
	end

    def self.faves term
        get('/get', query: { rId: term }) ["recipes"]
    end


end

app/models/user.rb
class User < ApplicationRecord

	has_secure_password 
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user 

def current_user 
  @current_user ||= User.find(session[:user_id]) if session[:user_id] 
end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.all
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new(:user => current_user.id, :recipe => params[:id])
    @id_r = params[:id]
    @recipe = Recipe.find(@id_r)
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { render :success, notice: 'Favorite was successfully created.' }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: 'Recipe was unfavorited.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.require(:favorite).permit(:user, :recipe)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  before_action :require_user, only: [:index, :show]
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def search
    @search_term = params[:ingredient]
    @recipes = Recipe.for(@search_term)
  end

  def show
    @id_r = params[:id]
    @recipe = Recipe.find(@id_r)
  end
  
  def browse
  	@rand_num = params[:random]
    @rand_recipes = Recipe.for(@rand_num)
  end

  def faves
    @ids = @recipes
    @faves = Recipe.for(@ids)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  @user = User.find_by_email(params[:session][:email])
  if @user && @user.authenticate(params[:session][:password])
    session[:user_id] = @user.id
    redirect_to '/home'
  else
    redirect_to '/login'
  end 
end

def destroy 
  session[:user_id] = nil 
  redirect_to '/login' 
end

def profile
  @user_favorite = Favorite.where(user: current_user.id)
  @ids = @user_favorite
  @faves = Recipe.for(@ids)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  @user = User.new
end

def create 
  @user = User.new(user_params) 
  if @user.save
    session[:user_id] = @user.id 
    redirect_to '/home' 
  else 
    redirect_to '/register' 
  end 
end

private
  def user_params
    params.require(:user).permit(:username, :email, :password, :location, :fname, :lname)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_form.html.erb
<%= form_for(favorite) do |f| %>
  <% if favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %>
    <%= f.number_field :user %>
  </div>

  <div class="field">
    <%= f.label :recipe %>
    <%= f.number_field :recipe %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favorites</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Recipe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.user %></td>
        <td><%= favorite.recipe %></td>
        <td><%= link_to 'Show', favorite %></td>
        <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
        <td><%= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
 <% this_recipe = @recipe %>

<h1> <%= current_user.fname %>, would you like to add  <% this_recipe["title"] %> to your favorites?</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/removed.html.erb
<center>

<h1><span class="glyphicon glyphicon-ok" style="color:#F4511E"></span></h2>
	<h1>Removed from Favorites!</h1><br/>

	<a href="/browse"><button type="submit" class="btn btn-default btn-lg">Go Back to Browsing</button></a> <a href="/home"><button type="submit" class="btn btn-default btn-lg">Search</button></a><br/><br/>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favorite.user %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @favorite.recipe %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/success.html.erb
<center>

<h1><span class="glyphicon glyphicon-ok" style="color:#F4511E"></span></h2>
	<h1>Added to Favorites!</h1><br/>

	<a href="/browse"><button type="submit" class="btn btn-default btn-lg">Go Back to Browsing</button></a> <a href="/home"><button type="submit" class="btn btn-default btn-lg">Search</button></a><br/><br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipEasy</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">

  <style>

  body {
      font: 400 15px Lato, sans-serif;
      line-height: 1.8;
      color: #818181;
  }
  h2 {
      font-size: 24px;
      text-transform: uppercase;
      color: #303030;
      font-weight: 600;
      margin-bottom: 30px;
  }
  h4 {
      font-size: 19px;
      line-height: 1.375em;
      color: #303030;
      font-weight: 400;
      margin-bottom: 30px;
  }
  .jumbotron {
      background-color: #f4511e;
      color: #fff;
      padding: 100px 25px;
      font-family: Montserrat, sans-serif;
  }
  .container-fluid {
      padding: 60px 50px;
  }
  .bg-grey {
      background-color: #f6f6f6;
  }
  .logo-small {
      color: #f4511e;
      font-size: 50px;
  }
  .logo {
      color: #f4511e;
      font-size: 200px;
  }
  .thumbnail {
      padding: 0 0 15px 0;
      border: none;
      border-radius: 0;
  }
  .thumbnail img {
      width: 100%;
      height: 100%;
      margin-bottom: 10px;
  }
  .carousel-control.right, .carousel-control.left {
      background-image: none;
      color: #f4511e;
  }
  .carousel-indicators li {
      border-color: #f4511e;
  }
  .carousel-indicators li.active {
      background-color: #f4511e;
  }
  .item h4 {
      font-size: 19px;
      line-height: 1.375em;
      font-weight: 400;
      font-style: italic;
      margin: 70px 0;
  }
  .item span {
      font-style: normal;
  }
  .panel {
      border: 1px solid #f4511e;
      border-radius:0 !important;
      transition: box-shadow 0.5s;
  }
  .panel:hover {
      box-shadow: 5px 0px 40px ;
  }
  .panel-footer .btn:hover {
      border: 1px solid #f4511e;
      background-color: #fff !important;
      color: #f4511e;
  }
  .panel-heading {
      color: #fff !important;
      background-color: #f4511e !important;
      padding: 25px;
      border-bottom: 1px solid transparent;
      border-top-left-radius: 0px;
      border-top-right-radius: 0px;
      border-bottom-left-radius: 0px;
      border-bottom-right-radius: 0px;
  }
  .panel-footer {
      background-color: white !important;
  }
  .panel-footer h3 {
      font-size: 32px;
  }
  .panel-footer h4 {
      color: #aaa;
      font-size: 14px;
  }
  .panel-footer .btn {
      margin: 15px 0;
      background-color: #f4511e;
      color: #fff;
  }
  .navbar {
      margin-bottom: 0;
      background-color: #f4511e;
      z-index: 9999;
      border: 0;
      font-size: 20px !important;
      line-height: 1.42857143 !important;
      letter-spacing: 4px;
      border-radius: 0;
      font-family: Montserrat, sans-serif;
  }
  .navbar li a, .navbar .navbar-brand {
      color: #fff !important;
  }
  .navbar-nav li a:hover, .navbar-nav li.active a {
      color: #f4511e !important;
      background-color: #fff !important;
  }
  .navbar-default .navbar-toggle {
      border-color: transparent;
      color: #fff !important;
  }
  footer .glyphicon {
      font-size: 20px;
      margin-bottom: 20px;
      color: #f4511e;
  }
  .slideanim {visibility:hidden;}
  .slide {
      animation-name: slide;
      -webkit-animation-name: slide;
      animation-duration: 1s;
      -webkit-animation-duration: 1s;
      visibility: visible;
  }
  @keyframes slide {
    0% {
      opacity: 0;
      transform: ;
    }
    100% {
      opacity: 1;
      transform: ;
    }
  }
  @-webkit-keyframes slide {
    0% {
      opacity: 0;
      -webkit-transform: ;
    }
    100% {
      opacity: 1;
      -webkit-transform: ;
    }
  }
  @media screen and (max-width: 768px) {
    .col-sm-4 {
      text-align: center;
      margin: 25px 0;
    }
    .btn-lg {
        width: 100%;
        margin-bottom: 35px;
    }
  }
  @media screen and (max-width: 480px) {
    .logo {
        font-size: 150px;
    }
  }

  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }

footer{
    text-align: center;
  }

  .glyphicon.glyphicon-cutlery {
    font-size: 200px;
	color:#f4511e;
}
  	
  </style>
  </head>


<body id="myPage">

<div id="fb-root"></div>

<!--This is the jdk for the facebook share button -->
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<!--Navigation bar -->
<div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home">RecipEasy</a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="/home"><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li><a href="/contact"><span class="glyphicon glyphicon-pencil"></span> Contact</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %> 
    <li><big><big><big>Welcome, <strong><%= current_user.fname %></strong>!</big></big></big></li> 
    <li><a href="/profile"><span class="glyphicon glyphicon-user"></span> My Profile</a></li>
    <li><a href="/browse"><span class="glyphicon glyphicon-file"></span> Browse Recipes</a></li>
    <li><%= link_to "Log Out", logout_path, method: "delete" %></li> 
<% else %>    

		<li><a href="/browse"><span class="glyphicon glyphicon-file"></span> Browse Recipes</a></li>
    <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Log In</a></li>
		<li><a href="/register"><span class="glyphicon glyphicon-log-in"></span> Register</a></li>

<% end %>
      </ul>
    </div>
  </div>

    
    <%= yield %>
<!--Footer-->
<footer>RecipEasy Project Fall 2016</footer>

  </body>
</html>

app/views/pages/contact.html.erb
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     
    </div>

    
  </div>



<div id="contact" class="container-fluid bg-grey">
  <h2 class="text-center">CONTACT</h2>
 <div class="row">
    <div class="col-sm-5">
      <p>Contact us and we'll get back to you within 24 hours.</p>
      <p><span class="glyphicon glyphicon-map-marker"></span> Aurora, US</p>
      <p><span class="glyphicon glyphicon-phone"></span>630-555-1234</p>
      <p><span class="glyphicon glyphicon-envelope"></span>recipeasy@aurora.edu</p>
	  
	  <div class="form-group">
    
      <input type="fname" class="form-control" id="fname" placeholder="Enter first name">
    </div>

    <div class="form-group">
     
      <input type="email" class="form-control" id="email" placeholder="Enter email">
    </div>
	
	<textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea><br>
      <div class="row">
        <div class="col-sm-12 form-group">
    <input type="submit" onclick="return confirm('Thank you for submitting your form!')" />
	<script>
            function submitForm() {
            document.contact-form.submit();
            document.contact-form.reset();
            }
        </script>
	 </form>
</div>
    </div>
      </div>
	  <div class="col-sm-5"></div>
	<div id="googleMap" style="height:400px;width:50%;"></div>
    </div>

	

<!-- Add Google Maps -->
<script src="https://maps.googleapis.com/maps/api/js"></script>
<script>
var myCenter = new google.maps.LatLng(41.7605556, -88.32);

function initialize() {
var mapProp = {
  center:myCenter,
  zoom:12,
  scrollwheel:false,
  draggable:false,
  mapTypeId:google.maps.MapTypeId.ROADMAP
  };

var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);

var marker = new google.maps.Marker({
  position:myCenter,
  });

marker.setMap(map);
}

google.maps.event.addDomListener(window, 'load', initialize);
</script>
<script>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


app/views/pages/home.html.erb
<div class="jumbotron text-center">
  <h1>RecipEasy </h1>
  <p>This website lets you make your own recipes with the ingredients you have in your own house!</p>

  <small>Please enter one or more ingredients separated by commas.</small><br/>
  <form class="form-inline" action='/recipes/search' method='GET'>
     <%= text_field_tag :ingredient, nil, :placeholder => 'chicken, cheese, lettuce...', :class => 'form-control' %>
    <%= submit_tag "Search", :class => 'btn btn-primary' %>
  </form>
</div>

<div id="about" class="container-fluid">
  <div class="row">
    <div class="col-sm-8">
      <h2>About RecipEasy</h2><br>
      <h4>Users will be able to search for recipes without having to login or register.</h4>
    <h4>However if a user wants to save or rate a recipe they will have to make an account.</h4>
    <% if !current_user %> 
      <br><form method="get" action="/register">
          <button type="submit" class="btn btn-default btn-lg">Let's Create An Account</button>
          </form>

          <div class="fb-share-button" data-href="https://localhost:3000/home.html.erb" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Flocalhost%3A3000%2Fhome.html.erb&amp;src=sdkpreparse">Share</a></div>

          <% end %> 
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-cutlery" style="color:#F4511E"></span>
    </div>
  </div>
</div>

<div id="portfolio" class="container-fluid text-center ">
  <h2>Recipes!</h2>
  <h4>Lets take a look at what has been created!</h4>
    <%= image_tag("food.jpg", :alt => "food", style: "height: 225px; width: 225px") %>
    <%= image_tag("fish.jpg", :alt => "fish", style: "height: 225px; width: 225px") %>
    <%= image_tag("chicken.jpg", :alt => "chicken", style: "height: 225px; width: 225px") %>  
		<%= image_tag("cucumbertuna.png", :alt => "cucumbertuna", style: "height: 225px; width: 225px") %> 
		<%= image_tag("sweetp.png", :alt => "sweetp", style: "height: 225px; width: 225px") %> 
    <%= image_tag("tomato.png", :alt => "tomato", style: "height: 225px; width: 225px") %>
    <%= image_tag("bacongua.png", :alt => "bacongua", style: "height: 225px; width: 225px") %>
    <%= image_tag("chickegg.png", :alt => "chickegg", style: "height: 225px; width: 225px") %>
</div>
  
  <div class="container-fluid text-center bg-grey">
  <div class="container">
  <h2>What our customers say</h2>
  <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">
    
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
	  <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <h4>"This website is amazing"<br><span style="font-style:normal;">Reese </span></h4>
      </div>
      <div class="item">
        <h4>"One word... WOW!!"<br><span style="font-style:normal;">Karla </span></h4>
      </div>
      <div class="item">
        <h4>"I have found so many delicious recipes"<br><span style="font-style:normal;">Greg Oij</span></h4>
      </div>
	  <div class="item">
        <h4>"I couldn't be happier with this website!"<br><span style="font-style:normal;">Jared</span></h4>
      </div>
    </div>
    
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hiddenhttp://localhost:3000/home#myCarousel="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
  </div>
</div>
  





<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <a href="#myPage" title="To Top">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>

app/views/pages/login.html.erb
<div id="contact" class="container-fluid bg-grey">

  <h2 class="text-center">Sigin With Recipe Generator</h2>
  <form>
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" placeholder="Enter email">
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="pwd" placeholder="Enter password">
    </div>
    <div class="checkbox">
      <label><input type="checkbox"> Remember me</label>
    </div>
    <button type="submit" class="btn btn-default">Login</button>
  </form>
</div>

app/views/pages/register.html.erb
  <div class="container">
 

     
  </div>

<div id="contact" class="container-fluid bg-grey">

  <h2 class="text-center">Create An Account With Recipe Generator</h2>
  <form>
<div class="form-group">
      <label for="name">First Name:</label>
      <input type="fname" class="form-control" id="fname" placeholder="Enter first name">
    </div>

<div class="form-group">
      <label for="lastName">Last Name:</label>
      <input type="lastName" class="form-control" id="lastName" placeholder="Enter last name">
    </div>

    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" placeholder="Enter email">
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="pwd" placeholder="Enter password">
    </div>
    <div class="checkbox">
      <label><input type="checkbox">Remember me</label>
    </div>
    <button type="submit" class="btn btn-default">Create Account</button>
  </form>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

app/views/pages/results.html.erb
 <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

  </div>
<div id="contact" class="container-fluid bg-grey">
  <h2 class="text-center">RESULTS</h2>
  <div class="row">
    <div class="col-sm-5">
     
    </div>
	</div>
</div>

app/views/pages/search_results.html.erb
<h2>Search Results:</h2>
<div>
    <% @recipes.each do |recipe| %>
    
# Not sure how to display results...
# Need to make results link to recipe...
    
    <% end %>
</div>

app/views/pages/userprofile.html.erb
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

  </div>

<div class="container w3-content w3-margin-top" style="max-width:1400px;">
   <div class="w3-row-padding" style="margin:0 -16px">
	
	<div class="w3-white w3-text-grey w3-card-4">
	 <div class="w3-display-container"
	
	<div class="w3-display-bottomleft w3-container w3-text-black">
            <h2>Jane Doe</h2>
          </div>
		  <%= image_tag('blank-profile.png', style: "height: 100px; width: 100px") %>
        </div>
        <div class="w3-container">
          <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i>User File</p>
          <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i>ex@mail.com</p>
          <hr>

          
    <!-- End Left Column -->
    </div>

    <!-- Right Column -->
    <div class="w3-twothird">
    

</div>

	

app/views/recipes/index.html.erb
<h1>Searching for - <%= @search_term %></h1>
<p>Powered By Food2Fork.com</p>
<% if (@recipes.nil? or @recipes == []) %>
<p> <h2>No recipes found.. Sorry</h2></p>
<% else %>

<table border="1">
 <tr>
 <th>Image</th>
 <th>Name</th>
 <th>Rank</th>
 </tr>
 <% @recipes.each do |course| %>
 <tr class=<%= cycle('even', 'odd') %>>
 <td><%= link_to(image_tag(course["image_url"], height: '100', width: '100'), course["f2f_url"])%></td>
 <td><%= link_to(course["title"], course["f2f_url"]) %></td>
 <td><%= course["social_rank"] %></td>
 </tr>
 <% end %>
</table>
<% end %>